server:
  port: 80

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: ucenter
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://out-zhoujundi.mysql.rds.aliyuncs.com:3307/nothing?useUnicode=true&amp;characterEncoding=UTF-8
    username: zjd_admin
    password: judy84711
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://chain

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery/eureka/


logging.level.org.springframework.security: DEBUG

logging.leve.org.springframework: DEBUG


security:
  oauth2:
    resource:
      filter-order: 3