server:
  port: 9000

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: ucenter
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.21.93:3307/nothing?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: G00dwi!!world
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/


logging.level.org.springframework.security: DEBUG

logging.leve.org.springframework: DEBUG


security:
  oauth2:
    resource:
      filter-order: 3